package interfaz;

public class Listadodeusuariosusuarioregistrado extends Listadousuarios {
	public VerlistadoglobaldeusuariosUsuarioregistrado _verlistadoglobaldeusuariosUsuarioregistrado;
	public Listadodeusuariosusuarioregistrado_item _item;
}